name: NodeJS CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Dependencies
      run: npm install

    - name: Unit Tests
      run: npm run test
    
    - name: End To End Tests
      run: npm run test:e2e

    - name: Deploy Application
      if: success()
      run: |
        npm run build
        pm2 restart PortfolioBackendAPI

    - name: Exit Bottleneck
      run: exit 1
      if: failure()
        