name: NodeJS CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: installDependencies
      run: npm install

    - name: testApplication
      run: npm run test

    - name: deployApplication
      if: sucess()
      run: |
        npm run build
        pm2 restart PortfolioBackendAPI

    - name: deployFailed
      if: failure()
        