name: NodeJS CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    env:
      DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
      DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD}}
      DATABASE_USER: ${{ secrets.DATABASE_USER }}
      JWT_SECRET_CONSTANT: ${{ secrets.JWT_SECRET_CONSTANT }}
      NODE_ENV: ${{ secrets.NODE_ENV }}

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Dependencies
      run: npm install

    - name: Unit Tests
      run: npm run test
    
    - name: End To End Tests
      run: npm run test:e2e

    - name: Deploy Application
      if: success()
      run: |
        npm run build
        cp -r dist/* ~/Desktop/Portfolio-Backend-Deploy
        pm2 restart PortfolioBackendAPI

    - name: Exit Bottleneck
      run: exit 1
      if: failure()
        